mqtt:
  server:
    address: 192.168.0.136

logging:
  level:
    com.baverage.backend: DEBUG

#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

spring.datasource.url: jdbc:mysql://192.168.0.107:3306/app
spring.datasource.username: iot
spring.datasource.password: 1234
spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.jpa.database-platform : org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto : update
