DROP TABLE IF EXISTS Tisch;
DROP TABLE IF EXISTS Platz;

CREATE TABLE IF NOT EXISTS Tisch (ID int NOT NULL AUTO_INCREMENT,name VARCHAR(10),PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS Platz (ID int NOT NULL AUTO_INCREMENT,name VARCHAR(10),PRIMARY KEY (ID), TISCH_ID int);

INSERT INTO Tisch(name) VALUES ("A");
INSERT INTO Tisch(name) VALUES ("B");
INSERT INTO Tisch(name) VALUES ("C");


INSERT INTO Platz (name,TISCH_ID) VALUES ("A",0);
INSERT INTO Platz (name,TISCH_ID) VALUES ("A",0);

INSERT INTO Platz (name,TISCH_ID) VALUES ("B",1);
INSERT INTO Platz (name,TISCH_ID) VALUES ("B",1);
INSERT INTO Platz (name,TISCH_ID) VALUES ("B",1);
INSERT INTO Platz (name,TISCH_ID) VALUES ("B",1);


INSERT INTO Platz (name,TISCH_ID) VALUES ("C",2);
INSERT INTO Platz (name,TISCH_ID) VALUES ("C",2);








